(define (problem blockworld-problem)
  (:domain blockworld)
  (:objects
    A C D E F G H I J K L - block
  )
  (:init
    (empty)
    (clear A) (on-table A)
    (clear C) (on-table C)
    (clear D) (on-table D)
    (clear E) (on-table E)
    (clear F) (on-table F)
    (clear G) (on-table G)
    (clear H) (on-table H)
    (clear I) (on-table I)
    (clear J) (on-table J)
    (clear K) (on-table K)
    (clear L) (on-table L)
  )
  (:goal
    (and
      (on A H)
      (on C E)
      (on D A)
      (on E J)
      (on F G)
      (on G K)
      (on H C)
      (on I D)
      (on J L)
      (on L F)
    )
  )
)