(define (problem block-stacking)
  (:domain blocksworld)
  (:objects A B C D F G H I K L - block)
  (:init
    (handempty)
    (clear A) (ontable A)
    (clear B) (ontable B)
    (clear C) (ontable C)
    (clear D) (ontable D)
    (clear F) (ontable F)
    (clear G) (ontable G)
    (clear H) (ontable H)
    (clear I) (ontable I)
    (clear K) (ontable K)
    (clear L) (ontable L)
  )
  (:goal
    (and
      (on A F)
      (on F I)
      (on I B)
      (on B H)
      (on H L)
      (on C D)
      (on D G)
      (on G K)
      (on K A)
    )
  )
)